import './globals.css';
import type { Metadata } from 'next';
import { Instrument_Sans } from 'next/font/google';

const InstrumentSans = Instrument_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Noted',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${InstrumentSans.className} min-h-[100svh] bg-dark text-white overflow-x-hidden`}
      >
        <main className="max-w-[1273px] mx-auto px-[24px]">{children}</main>
      </body>
    </html>
  );
}
